FROM bitwalker/alpine-elixir:1.6.0
RUN apk add bash imagemagick curl && rm -rf /var/cache/apk/*

ENV HOME=/opt/app/ SHELL=/bin/bash MIX_ENV=prod
WORKDIR /opt/app

COPY rest-api_release.tar .
RUN tar x -f rest-api_release.tar && rm rest-api_release.tar

EXPOSE 80
ENTRYPOINT ["bin/captain_fact"]
