FROM bitwalker/alpine-elixir:1.7.1
RUN apk add bash imagemagick curl && rm -rf /var/cache/apk/*

ENV HOME=/opt/app/ SHELL=/bin/bash MIX_ENV=prod
WORKDIR /opt/app

COPY cf_opengraph.tar .
RUN tar x -f cf_opengraph.tar && rm cf_opengraph.tar

EXPOSE 80
ENTRYPOINT ["bin/cf_opengraph"]
