FROM bitwalker/alpine-elixir:1.6.6
RUN apk add bash imagemagick curl && rm -rf /var/cache/apk/*

ENV HOME=/opt/app/ SHELL=/bin/bash MIX_ENV=prod
WORKDIR /opt/app

COPY atom-feed_release.tar .
RUN tar x -f atom-feed_release.tar && rm atom-feed_release.tar

EXPOSE 80
ENTRYPOINT ["bin/cf_atom_feed"]
