stages:
  - test
#  - release
  - cleanup

test:
  stage: test
  tags: [docker]
  before_script:
    - docker network create network_testing
    - docker run -d
      --name postgres_testing
      --network network_testing
      -e POSTGRES_DB=captain_fact_test
      -e POSTGRES_PASSWORD=postgres
      postgres:9.6
  script:
    - docker run --rm
      --network network_testing
      -v $(pwd):/opt/app
      -e MIX_ENV=test
      -e POSTGRES_HOST=postgres_testing
      betree/alpine-elixir-gcc:1.5.1
      /bin/sh -c
      "env && mix local.hex --force && mix local.rebar --force && mix deps.get && mix ecto.setup && mix test"
  after_script:
    - docker stop postgres_testing || /bin/true
    - docker rm postgres_testing || /bin/true
    - docker network rm network_testing || /bin/true

# Dirty fix : files created in docker are owned by root. We change permissions so gitlab-runner can delete them
cleanup:
  stage: cleanup
  tags: [docker]
  when: always
  script: docker run -v $(pwd):/opt/app --rm alpine:latest chmod -R 777 /opt/app/{_build,deps}