stages:
  - test
#  - release

# Config to be passed to associated services - used for test
variables:
  CONTINUOUS_INTEGRATION: "true"
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: captain_fact_test
  BUILD_IMAGE: build-$CI_PROJECT_ID:$CI_BUILD_REF
  BUILD_VOLUME: build_data-$CI_PROJECT_ID-$CI_BUILD_REF

test:
  stage: test
  image: bitwalker/alpine-elixir:1.5.1
  tags: [docker]
  services:
    - postgres
  script:
    - mix test
