stages:
  - test
#  - release

test:
  stage: test
  tags: [docker]
  before_script:
    - docker run -d
      --name postgres_testing
      -e POSTGRES_DB=captain_fact_test
      -e POSTGRES_PASSWORD=postgres
      postgres:9.6
  script:
    - docker run --rm
      --link postgres_testing:postgres
      -e CONTINUOUS_INTEGRATION=true
      -v $(pwd):/opt/app
      bitwalker/alpine-elixir:1.5.1
      /bin/sh -c "mix local.hex --force && mix local.rebar --force && mix deps.get && mix ecto.setup && mix test"
  after_script:
    - docker stop postgres_testing
    - docker rm postgres_testing