stages:
  - prepare
  - test
#  - release
  - cleanup

prepare:
  stage: prepare
  tags: [docker]
  script:
    - docker run --name build_cache -v /opt  busybox /bin/true
    - docker cp $(pwd) build_cache:/opt/app

test:
  stage: test
  tags: [docker]
  before_script:
    - docker network create network_testing
    - docker run -d
      --name postgres_testing
      --network network_testing
      -e POSTGRES_DB=captain_fact_test
      -e POSTGRES_PASSWORD=postgres
      postgres:9.6
  script:
    - docker run --rm
      --network network_testing
      --volumes-from build_cache
      -e POSTGRES_HOST=postgres_testing
      betree/alpine-elixir-gcc:1.5.1
      /bin/sh -c
      "env && mix local.hex --force && mix local.rebar --force && mix deps.get && mix ecto.setup && mix test"
  after_script:
    - docker stop postgres_testing
    - docker rm postgres_testing
    - docker network rm network_testing

cleanup:
  stage: cleanup
  tags: [docker]
  when: always
  script:
    - docker rm build_cache