stages:
  - name: test
  - name: release

# ---- Jobs ----

jobs:
  include:
    - stage: test
      language: elixir
      elixir: "1.6"
      otp_release: "21.0"
      cache: { paths: ["_build", "deps"] }
      addons: { postgresql: "9.6" }
      env:
        - MIX_ENV=test
      before_script:
        - mix format --check-formatted
        - mix local.hex --force
        - mix local.rebar --force
        - mix deps.get
        - mix ecto.create
        - mix ecto.migrate
      script:
        - mix coveralls.travis --umbrella

    - stage: release
      if: branch IN (master, staging) AND type != pull_request
      language: generic
      sudo: required
      services: [docker]
      script:
        - ./rel/release.sh $TRAVIS_BRANCH
