# ----- Config -----

stages: 
  - name: test
  - name: build
  - name: package
  - name: release

env:
  # Temporary build image
  CF_API_BUILD_IMAGE: captain-fact-api-build:$CI_COMMIT_REF_SLUG
  # Releases
  CF_API_REST_IMAGE: captainfact/rest-api:$CI_COMMIT_REF_SLUG
  CF_API_GRAPHQL_IMAGE: captainfact/graphql-api:$CI_COMMIT_REF_SLUG
  CF_API_ATOM_FEED: captainfact/atom-feed:$CI_COMMIT_REF_SLUG
  CF_API_OPENGRAPH_IMAGE: captainfact/opengraph:$CI_COMMIT_REF_SLUG

# ---- Jobs ----

jobs:
  include:
    - stage: test
      language: elixir
      elixir: '1.6'
      otp_release: '21.0'
      cache: {paths: ["_build", "deps"]}
      services: [postgresql]
      env:
        - MIX_ENV=test
        - CF_DB_HOSTNAME=postgres
      before_script:
        - mix local.hex --force
        - mix local.rebar --force
        - mix deps.get
        - mix ecto.create
        - mix ecto.migrate
      script:
        - mix coveralls.travis --umbrella
        - mix format --check-formatted

