jobs:
  include:
    - stage: test
      name: Check Format
      language: elixir
      elixir: "1.6"
      otp_release: "21.0"
      cache: { paths: ["_build", "deps"] }
      env:
        - MIX_ENV=test
      script:
        - mix format --check-formatted

    - stage: test
      name: Unit test
      language: elixir
      elixir: "1.6"
      otp_release: "21.0"
      cache: { paths: ["_build", "deps"] }
      addons: { postgresql: "9.6" }
      env:
        - MIX_ENV=test
      before_script:
        - mix local.hex --force
        - mix local.rebar --force
        - mix deps.get
        - mix ecto.create
        - mix ecto.migrate
      script:
        - mix coveralls.travis --umbrella

    - stage: release
      if: type != pull_request AND (branch IN (master, staging) OR tag =~ ^v\d+)
      language: generic
      sudo: required
      services: [docker]
      script:
        - ./rel/release.sh $TRAVIS_BRANCH
