FROM bitwalker/alpine-elixir:1.5.1
ENV DEBIAN_FRONTEND=noninteractive

EXPOSE 8000
ENV MIX_ENV=prod REPLACE_OS_VARS=true SHELL=/bin/bash

WORKDIR /app
COPY ./captain_fact.tar.gz ./
RUN tar xfz captain_fact.tar.gz

ENTRYPOINT ["bin/captain_fact"]