FROM bitwalker/alpine-elixir:1.5.1

RUN apk add gcc make musl-dev

ENV HOME=/opt/app/ TERM=xterm

WORKDIR /opt/app
ENV MIX_ENV=prod REPLACE_OS_VARS=true

# Cache elixir deps
COPY mix.exs mix.lock ./
RUN mix deps.get
COPY config ./config
RUN mix deps.compile

COPY . .
RUN mix release --env=prod
