import EctoEnum

defenum(
  DB.Type.NotificationType,
  :notification_type,
  [
    # Default notification type, for when type is unknown
    :default,
    # Notifications generated by `create_notifications` job
    :reply_to_comment,
    :new_comment,
    :new_statement,
    :new_speaker,
    :updated_statement,
    :updated_video,
    :updated_speaker,
    # Notifications below are meant to be dispatched manualy
    :new_achievement,
    :email_confirmed
  ]
)
