name: E2E/Integration tests

on: [push]

env:
  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

jobs:
  cypress:
    runs-on: ubuntu-latest
    services:
      db:
        image: captainfact/dev-db:latest
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout API
        uses: actions/checkout@v1
      - name: Restore Elixir cache
        uses: actions/cache@v1
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-mix-
      - name: Restore Elixir build folder
        uses: actions/cache@v1
        with:
          path: build
          key: ${{ runner.os }}-mix-build
      - uses: actions/setup-elixir@v1.1.0
        with:
          otp-version: 21.x
          elixir-version: 1.6.x
      - name: Install API's dependencies
        run: mix deps.get
      - name: Compile dependencies
        run: mix deps.compile
      - name: Compile project
        run: mix compile
      - name: Prepare DB
        run: mix ecto.create && mix ecto.migrate
      - uses: actions/setup-node@v1
      - name: Checkout Frontend
        uses: actions/checkout@v2
        with:
          repository: CaptainFact/captain-fact-frontend
          ref: refs/heads/staging
          path: ./captain-fact-frontend
      - name: Restore node_modules
        uses: actions/cache@v1
        id: node-modules
        with:
          path: captain-fact-frontend/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('captain-fact-frontend/package-lock.json') }}
      - name: Install Frontend's dependencies
        working-directory: captain-fact-frontend
        run: npm ci --prefer-offline --no-audit
      - run: ./scripts/run_e2e_ci.sh
