name: Release

on:
  push:
    branches:
      - master
      - staging

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  push-to-docker-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: docker build --build-arg BUILD_ENV=${GITHUB_REF##*/} -t captainfact/api:${GITHUB_REF##*/} .
      - run: docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - run: docker push captainfact/api:${GITHUB_REF##*/}
