name: Release

on:
  push:
    branches:
      - master
      - staging
      - release/docker-image

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  push-to-docker-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: docker build --build-arg BUILD_ENV=staging -t captainfact/api:test .
      - run: docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - run: docker push captainfact/api:test
